/* Auto-generated from Google Earth KML: Greers Ferry Lake Cove Names & Locations */
const COVE_PINS = [
  {
    "id": "cove-drip-creek-8129",
    "name": "Drip Creek",
    "lat": 35.572575,
    "lng": -92.063734,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-brittany-cove",
    "name": "Brittany Cove",
    "lat": 35.558451,
    "lng": -92.081319,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-twin-coves",
    "name": "Twin Coves",
    "lat": 35.55878,
    "lng": -92.076148,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-kidney-cove",
    "name": "Kidney Cove",
    "lat": 35.529065,
    "lng": -92.054001,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-silver-ridge-peninsula",
    "name": "Silver Ridge Peninsula",
    "lat": 35.516682,
    "lng": -92.052897,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-tannenbaum",
    "name": "Tannenbaum",
    "lat": 35.524065,
    "lng": -92.061556,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-goat-island",
    "name": "Goat Island",
    "lat": 35.519176,
    "lng": -92.086056,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\ud83c\udfdd",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-bird-island",
    "name": "Bird Island",
    "lat": 35.528582,
    "lng": -92.024903,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\ud83c\udfdd",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-eden-isle-marina",
    "name": "Eden Isle Marina",
    "lat": 35.501338,
    "lng": -92.095372,
    "category": "Marina",
    "color": "#7aa2ff",
    "emoji": "\u2693",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-eden-isle",
    "name": "Eden Isle",
    "lat": 35.505689,
    "lng": -92.102956,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-lake-eden",
    "name": "Lake Eden",
    "lat": 35.499082,
    "lng": -92.10374,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-big-dike",
    "name": "Big Dike",
    "lat": 35.476262,
    "lng": -92.08944,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-little-dike",
    "name": "Little Dike",
    "lat": 35.491561,
    "lng": -92.062678,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-old-road-1856",
    "name": "Old Road",
    "lat": 35.498946,
    "lng": -92.102843,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-miller-s-point",
    "name": "Miller's Point",
    "lat": 35.510669,
    "lng": -92.134681,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-diamond-bluff",
    "name": "Diamond Bluff",
    "lat": 35.516069,
    "lng": -92.190839,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\u26f0",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-salt-creek",
    "name": "Salt Creek",
    "lat": 35.523876,
    "lng": -92.209812,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-tortoise-bay",
    "name": "Tortoise Bay",
    "lat": 35.538393,
    "lng": -92.213294,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-parker-island",
    "name": "Parker Island",
    "lat": 35.537814,
    "lng": -92.205221,
    "category": "Park",
    "color": "#4ecdc4",
    "emoji": "\ud83c\udfd6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-bondair",
    "name": "Bondair",
    "lat": 35.538902,
    "lng": -92.182669,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-shiloh-marina",
    "name": "Shiloh Marina",
    "lat": 35.539241,
    "lng": -92.146164,
    "category": "Marina",
    "color": "#7aa2ff",
    "emoji": "\u2693",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-puddin-ridge",
    "name": "Puddin' Ridge",
    "lat": 35.543227,
    "lng": -92.114992,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-hurricane-bay",
    "name": "Hurricane Bay",
    "lat": 35.549944,
    "lng": -92.177319,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-lacey-s-narrows-marina",
    "name": "Lacey's Narrows Marina",
    "lat": 35.559644,
    "lng": -92.19424,
    "category": "Marina",
    "color": "#7aa2ff",
    "emoji": "\u2693",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-the-narrows-main-channel",
    "name": "The Narrows/Main Channel",
    "lat": 35.551077,
    "lng": -92.186995,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-lake-ice-rd",
    "name": "Lake Ice Rd.",
    "lat": 35.539431,
    "lng": -92.207449,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-poker-hill",
    "name": "Poker Hill",
    "lat": 35.578382,
    "lng": -92.202442,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-higden-bay",
    "name": "Higden Bay",
    "lat": 35.571769,
    "lng": -92.213835,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-mill-creek",
    "name": "Mill Creek",
    "lat": 35.582677,
    "lng": -92.219186,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-five-fingers",
    "name": "Five Fingers",
    "lat": 35.588646,
    "lng": -92.228181,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-mystic-isle",
    "name": "Mystic Isle",
    "lat": 35.606547,
    "lng": -92.173129,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-jansen-s-lakefront-restaurant",
    "name": "Jansen's Lakefront Restaurant",
    "lat": 35.602316,
    "lng": -92.187217,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-middle-fork",
    "name": "Middle Fork",
    "lat": 35.614166,
    "lng": -92.194603,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-skypoint",
    "name": "Skypoint",
    "lat": 35.604237,
    "lng": -92.140621,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-midway-bluffs",
    "name": "Midway Bluffs",
    "lat": 35.607176,
    "lng": -92.126071,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\u26f0",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-hill-creek-marina",
    "name": "Hill Creek Marina",
    "lat": 35.607768,
    "lng": -92.149141,
    "category": "Marina",
    "color": "#7aa2ff",
    "emoji": "\u2693",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-shirley",
    "name": "Shirley",
    "lat": 35.65542,
    "lng": -92.32029,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-wild-goose-creek-2159",
    "name": "Wild Goose Creek",
    "lat": 35.656606,
    "lng": -92.219716,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-birdie-hollow",
    "name": "Birdie Hollow",
    "lat": 35.643879,
    "lng": -92.221298,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-brewer",
    "name": "Brewer",
    "lat": 35.622387,
    "lng": -92.209168,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-shop-hollow",
    "name": "Shop Hollow",
    "lat": 35.626688,
    "lng": -92.19332,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-brush-creek-5740",
    "name": "Brush Creek",
    "lat": 35.626015,
    "lng": -92.187439,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-stewart-hollow",
    "name": "Stewart Hollow",
    "lat": 35.624008,
    "lng": -92.212588,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-punchin-hollow",
    "name": "Punchin Hollow",
    "lat": 35.641238,
    "lng": -92.215344,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-sandiff-river",
    "name": "Sandiff River",
    "lat": 35.65044,
    "lng": -92.225923,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-indian-creek",
    "name": "Indian Creek",
    "lat": 35.665245,
    "lng": -92.254764,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-greenbrier-creek",
    "name": "Greenbrier Creek",
    "lat": 35.666634,
    "lng": -92.2615,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-ship-branch",
    "name": "Ship Branch",
    "lat": 35.665974,
    "lng": -92.267352,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-weaver-creek-526",
    "name": "Weaver Creek",
    "lat": 35.644808,
    "lng": -92.301008,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-hump-hollow",
    "name": "Hump Hollow",
    "lat": 35.644036,
    "lng": -92.297064,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-weaver-creek-3803",
    "name": "Weaver Creek",
    "lat": 35.639589,
    "lng": -92.337126,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-big-branch-676",
    "name": "Big Branch",
    "lat": 35.646104,
    "lng": -92.334988,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-harper-s-cove",
    "name": "Harper's Cove",
    "lat": 35.552269,
    "lng": -92.361566,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-dave-creek",
    "name": "Dave Creek",
    "lat": 35.586335,
    "lng": -92.266565,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-hooten-hollow-7063",
    "name": "Hooten Hollow",
    "lat": 35.576702,
    "lng": -92.250954,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-grand-isle",
    "name": "Grand Isle",
    "lat": 35.578388,
    "lng": -92.237088,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-lynn-creek",
    "name": "Lynn Creek",
    "lat": 35.58301,
    "lng": -92.289688,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-enchanted-peninsula",
    "name": "Enchanted Peninsula",
    "lat": 35.57754,
    "lng": -92.247412,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-snakehead-cove",
    "name": "Snakehead Cove",
    "lat": 35.5749,
    "lng": -92.283759,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-boat-ridge-island",
    "name": "Boat Ridge Island",
    "lat": 35.553687,
    "lng": -92.315971,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\ud83c\udfdd",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-green-creek",
    "name": "Green Creek",
    "lat": 35.556865,
    "lng": -92.317727,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-party-cove-4935",
    "name": "Party Cove",
    "lat": 35.5605,
    "lng": -92.332248,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-thompson-creek",
    "name": "Thompson Creek",
    "lat": 35.562339,
    "lng": -92.335217,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-south-fork",
    "name": "South Fork",
    "lat": 35.554396,
    "lng": -92.323664,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-peter-rock-point",
    "name": "Peter Rock Point",
    "lat": 35.545109,
    "lng": -92.357545,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-south-fork-river",
    "name": "South Fork River",
    "lat": 35.564818,
    "lng": -92.37541,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-archey-creek",
    "name": "Archey Creek",
    "lat": 35.590336,
    "lng": -92.446911,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-pee-dee-creek",
    "name": "Pee Dee Creek",
    "lat": 35.591895,
    "lng": -92.413845,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-choctaw-creek",
    "name": "Choctaw Creek",
    "lat": 35.531929,
    "lng": -92.363545,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-big-branch-9457",
    "name": "Big Branch",
    "lat": 35.523905,
    "lng": -92.423314,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-emerald-isle",
    "name": "Emerald Isle",
    "lat": 35.552498,
    "lng": -92.335119,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-eglantine",
    "name": "Eglantine",
    "lat": 35.562269,
    "lng": -92.309703,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-quiet-cove",
    "name": "Quiet Cove",
    "lat": 35.562445,
    "lng": -92.318539,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-steven-s-point",
    "name": "Steven's Point",
    "lat": 35.544029,
    "lng": -92.312428,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-bailey-hollow",
    "name": "Bailey Hollow",
    "lat": 35.546969,
    "lng": -92.307948,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-banker-s-cove",
    "name": "Banker's Cove",
    "lat": 35.543166,
    "lng": -92.307636,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-tee-pee-cove",
    "name": "Tee Pee Cove",
    "lat": 35.575136,
    "lng": -92.27929,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-lakeshore-dr",
    "name": "Lakeshore Dr.",
    "lat": 35.581062,
    "lng": -92.260998,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-kinderhook",
    "name": "Kinderhook",
    "lat": 35.595971,
    "lng": -92.206855,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-eva-turney-hollow",
    "name": "Eva Turney Hollow",
    "lat": 35.597265,
    "lng": -92.210408,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-edgewater",
    "name": "Edgewater",
    "lat": 35.59721,
    "lng": -92.201389,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-old-train-bridge",
    "name": "Old Train Bridge",
    "lat": 35.602366,
    "lng": -92.188046,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\ud83c\udf09",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-salt-cave",
    "name": "Salt Cave",
    "lat": 35.593215,
    "lng": -92.171948,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-davidson-circle",
    "name": "Davidson Circle",
    "lat": 35.601395,
    "lng": -92.148001,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-launch-ramp-rd",
    "name": "Launch Ramp Rd.",
    "lat": 35.592518,
    "lng": -92.163329,
    "category": "Ramp",
    "color": "#4ecdc4",
    "emoji": "\ud83d\udef6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-sylvan-shores",
    "name": "Sylvan Shores",
    "lat": 35.605128,
    "lng": -92.13587,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-oid-sunny-slope-rd",
    "name": "OId Sunny Slope Rd.",
    "lat": 35.607802,
    "lng": -92.126389,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-midway-bridge",
    "name": "Midway Bridge",
    "lat": 35.606765,
    "lng": -92.12823,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\ud83c\udf09",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-devil-s-bluff",
    "name": "Devil's Bluff",
    "lat": 35.605605,
    "lng": -92.12794,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\u26f0",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-frontier-canyon",
    "name": "Frontier Canyon",
    "lat": 35.61872,
    "lng": -92.085286,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-hooten-hollow-8283",
    "name": "Hooten Hollow",
    "lat": 35.623662,
    "lng": -92.09322,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-wildcat-hollow",
    "name": "Wildcat Hollow",
    "lat": 35.621324,
    "lng": -92.096293,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-prim-rd-hwy-263",
    "name": "Prim Rd. Hwy. 263",
    "lat": 35.633168,
    "lng": -92.053026,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-beech-fork",
    "name": "Beech Fork",
    "lat": 35.658116,
    "lng": -92.015646,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-cedar-creek",
    "name": "Cedar Creek",
    "lat": 35.653289,
    "lng": -91.998734,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-yellow-branch",
    "name": "Yellow Branch",
    "lat": 35.640439,
    "lng": -92.030276,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-everett-ridge",
    "name": "Everett Ridge",
    "lat": 35.681346,
    "lng": -92.055548,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-bear-hollow",
    "name": "Bear Hollow",
    "lat": 35.685124,
    "lng": -92.056908,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-turkey-creek-9446",
    "name": "Turkey Creek",
    "lat": 35.662339,
    "lng": -92.031966,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-turkey-creek-7527",
    "name": "Turkey Creek",
    "lat": 35.731073,
    "lng": -92.085327,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-tick-creek",
    "name": "Tick Creek",
    "lat": 35.734632,
    "lng": -92.295749,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-porter-hollow",
    "name": "Porter Hollow",
    "lat": 35.73263,
    "lng": -92.294619,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-little-wild-goose-creek",
    "name": "Little Wild Goose Creek",
    "lat": 35.674789,
    "lng": -92.234011,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-wild-goose-creek-6225",
    "name": "Wild Goose Creek",
    "lat": 35.67674,
    "lng": -92.222577,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-backbone-ridge",
    "name": "Backbone Ridge",
    "lat": 35.682405,
    "lng": -92.229601,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-hill-creek",
    "name": "Hill Creek",
    "lat": 35.635613,
    "lng": -92.155114,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-bird-hollow",
    "name": "Bird Hollow",
    "lat": 35.615545,
    "lng": -92.197936,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-party-cove-3552",
    "name": "Party Cove",
    "lat": 35.607046,
    "lng": -92.125131,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-big-lake",
    "name": "Big Lake",
    "lat": 35.525788,
    "lng": -91.991204,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-wackley-hollow",
    "name": "Wackley Hollow",
    "lat": 35.529761,
    "lng": -91.987937,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-robinson-hollow",
    "name": "Robinson Hollow",
    "lat": 35.533969,
    "lng": -91.995795,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-asphalt-beach",
    "name": "Asphalt Beach",
    "lat": 35.527847,
    "lng": -92.012608,
    "category": "Park",
    "color": "#4ecdc4",
    "emoji": "\ud83c\udfd6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-us-army-corps-of-engineers",
    "name": "US Army Corps of Engineers",
    "lat": 35.521815,
    "lng": -91.999412,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-little-red-river",
    "name": "Little Red River",
    "lat": 35.51819,
    "lng": -91.995799,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-old-hwy-25-park-beach",
    "name": "Old Hwy 25 Park Beach",
    "lat": 35.5342,
    "lng": -92.015465,
    "category": "Park",
    "color": "#4ecdc4",
    "emoji": "\ud83c\udfd6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-peter-creek-9938",
    "name": "Peter Creek",
    "lat": 35.56285,
    "lng": -91.977983,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-copperas-spring-hollow",
    "name": "Copperas Spring Hollow",
    "lat": 35.549816,
    "lng": -92.024945,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-little-peter-creek",
    "name": "Little Peter Creek",
    "lat": 35.56502,
    "lng": -92.015573,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-drip-creek-9589",
    "name": "Drip Creek",
    "lat": 35.545926,
    "lng": -92.070825,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-dug-hill-rd",
    "name": "Dug Hill Rd.",
    "lat": 35.55346,
    "lng": -92.017961,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-peter-creek-3429",
    "name": "Peter Creek",
    "lat": 35.534575,
    "lng": -92.031343,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-collin-s-creek",
    "name": "Collin\u2019s Creek",
    "lat": 35.514068,
    "lng": -91.991271,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-cow-shoals",
    "name": "Cow Shoals",
    "lat": 35.513478,
    "lng": -91.938331,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-prior-mountain",
    "name": "Prior Mountain",
    "lat": 35.491686,
    "lng": -92.231959,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-north-fork-cadron-creek",
    "name": "North Fork Cadron Creek",
    "lat": 35.489197,
    "lng": -92.228545,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-sugarloaf-mountain-the-lookout",
    "name": "Sugarloaf Mountain/The Lookout",
    "lat": 35.490733,
    "lng": -91.985694,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-rocky-top-falls",
    "name": "Rocky Top Falls",
    "lat": 35.581407,
    "lng": -92.288113,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\u26f0",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-pebble-beach",
    "name": "Pebble Beach",
    "lat": 35.492345,
    "lng": -92.054395,
    "category": "Park",
    "color": "#4ecdc4",
    "emoji": "\ud83c\udfd6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-cove-creek",
    "name": "Cove Creek",
    "lat": 35.471211,
    "lng": -92.144418,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-devil-s-fork",
    "name": "Devil's Fork",
    "lat": 35.590761,
    "lng": -92.17961,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-narrows-launch",
    "name": "Narrows Launch",
    "lat": 35.563314,
    "lng": -92.196252,
    "category": "Ramp",
    "color": "#4ecdc4",
    "emoji": "\ud83d\udef6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-devil-s-fork-launch",
    "name": "Devil's Fork Launch",
    "lat": 35.591872,
    "lng": -92.18013,
    "category": "Ramp",
    "color": "#4ecdc4",
    "emoji": "\ud83d\udef6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-brush-creek-1348",
    "name": "Brush Creek",
    "lat": 35.626058,
    "lng": -92.187745,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-hill-creek-boat-ramp",
    "name": "Hill Creek Boat Ramp",
    "lat": 35.608461,
    "lng": -92.146541,
    "category": "Ramp",
    "color": "#4ecdc4",
    "emoji": "\ud83d\udef6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-cove-creek-boat-launch",
    "name": "Cove Creek Boat Launch",
    "lat": 35.464858,
    "lng": -92.153024,
    "category": "Ramp",
    "color": "#4ecdc4",
    "emoji": "\ud83d\udef6",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-old-road-5065",
    "name": "Old Road",
    "lat": 35.494462,
    "lng": -92.099893,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-old-road-9879",
    "name": "Old Road",
    "lat": 35.566583,
    "lng": -92.214436,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-mastercraft-alley",
    "name": "Mastercraft Alley",
    "lat": 35.620144,
    "lng": -92.190136,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-fairfield-bay-bluffs-cliffs",
    "name": "Fairfield Bay Bluffs/Cliffs",
    "lat": 35.573353,
    "lng": -92.280515,
    "category": "Landmark",
    "color": "#e8c98a",
    "emoji": "\u26f0",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  },
  {
    "id": "cove-budd-creek",
    "name": "Budd Creek",
    "lat": 35.55657,
    "lng": -92.121844,
    "category": "Cove",
    "color": "#8ecae6",
    "emoji": "\ud83c\udf3f",
    "fact": "Local cove / shoreline name from the Greers Ferry Lake cove map.",
    "tip": "Community-named place. Depths change with pool elevation."
  }
];
